application: webmemcache
version: 1
runtime: python
api_version: 1

handlers:

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /js/(.*)
  static_files: static/js/\1
  upload: static/js/(.*)

- url: /image/(.*)
  static_files: static/image/\1
  upload: static/image/(.*)

- url: .*
  script: main.py
